package com.example.MyBookShopApp.data.Entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.List;

@Getter
@Setter
@Entity
@Table(name = "author")
public class Author {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty("author id is generated by db")
    private Long id;
    @JsonIgnore
    @OneToMany(mappedBy = "author")
    private List<Book> bookList;
    @ApiModelProperty("photo is author")
    private String photo;
    @ApiModelProperty("slug for author")
    private String slug;
    @ApiModelProperty(value = "name for author", example = "Bob B.")
    private String name;
    @ApiModelProperty(value = "description for author")
    private String description;

    public Author() {

    }

    public String toString() {
        return name;
    }
}
